### ISSUE TITLE
Exception in thread "main" clojure.lang.ExceptionInfo: unknown function 'glob.match' {:type :parser-exception}

### ISSUE THREAD

**Issue by rai-prashanna** [borgeby/jarl#174]
My plan.json contains glob.match function which seems that Jarl doesn't support glob.match function. 
My stack trace is as follows.  
Exception in thread "main" clojure.lang.ExceptionInfo: unknown function 'glob.match' {:type :parser-exception}
	at jarl.parser$make_builtin_func.invokeStatic(parser.cljc:291)
	at jarl.parser$make_builtin_func.invoke(parser.cljc:287)
	at jarl.parser$make_builtin_funcs$assoc_builtin_func__9616.invoke(parser.cljc:298)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at jarl.parser$make_builtin_funcs.invokeStatic(parser.cljc:300)
	at jarl.parser$make_builtin_funcs.invoke(parser.cljc:295)
	at jarl.parser$parse.invokeStatic(parser.cljc:310)
	at jarl.parser$parse.invoke(parser.cljc:302)
	at jarl.parser$parse.invokeStatic(parser.cljc:305)
	at jarl.parser$parse.invoke(parser.cljc:302)
	at jarl.parser$parse_json.invokeStatic(parser.cljc:316)
	at jarl.parser$parse_json.invoke(parser.cljc:313)
	at jarl.api$_jarl_parser_parse.invokeStatic(api.clj:74)
	at jarl.api$_jarl_parser_parse.invoke(api.clj:73)
	at by.borge.jarl.internal.Parser.parse(Unknown Source)
	at by.borge.jarl.Jarl$Builder.build(Jarl.java:53)
	at com.prai.opa.JARLAuthz.initJARLMode(JARLAuthz.java:40)

**Comment by rai-prashanna** [comment]
I notice that Jarl was never meant to support glob.match function as mentioned in this link 
https://github.com/borgeby/jarl/blob/main/doc/builtins.md
So, I am closing this issue.

**Comment by anderseknert** [comment]
We definitely would want to support that, and all builtins eventually! But the glob matching functions are complicated to port, as there's a lot of custom logic in those, and no equivalent package for the JVM. So we'd need to put a lot of effort into that.

**Comment by anderseknert** [comment]
@johanfylling we should make the error message nicer for when an unsupported built-in function is called 😅
